In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./data/wine_cleared.zip")

# 2. Создание признаков

In [3]:
data = df.copy()

## Разбор числовых величин

Создадим новый признак price_round, означающий округлённую до целого числа цену за бутылку вина

In [9]:
data["price_round"] = data["price"].round().astype(int)
data.head(3)

,Unnamed: 0,country,description,designation,points,price,province,region_1,taster_name,taster_twitter_handle,title,variety,winery,price_round
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,35.363389,Sicily & Sardinia,Etna,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,35
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.000000,Douro,unknown,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,15
2,2,US,"Tart and snappy, the flavors of lime flesh and...",unknown,87,14.000000,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,14

## Разбор текста

Выполните код для нахождения года вина при помощи регулярного выражения

In [43]:
regex = "\d{4}"  # регулярное выражение для нахождения чисел
data["year"] = data["title"].str.findall(regex).str.get(0)
data.head(3)

,Unnamed: 0,country,description,designation,points,price,province,region_1,taster_name,taster_twitter_handle,title,variety,winery,price_round,year,is_usa,is_france,is_italy,old_wine
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,35.363389,Sicily & Sardinia,Etna,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,35,2013,0,0,1,0
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.000000,Douro,unknown,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,15,2011,0,0,0,0
2,2,US,"Tart and snappy, the flavors of lime flesh and...",unknown,87,14.000000,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,14,2013,1,0,0,0

## Разбор категорий

Создать новый бинарный признак is_usa и присвоить ему 1 в случае, если вино произведено в США, иначе — 0

In [44]:
data["is_usa"] = data["country"].apply(lambda x: 1 if x == "US" else 0)

### Задание 2.1

Выберите из списка две самых популярных (помимо США) страны, производящих вино

In [45]:
data["country"].value_counts()

country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Serbia                       12
Czech Republic               12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Bosnia and Herzegovina        2
Armenia                       2
Slovakia                      1
China                         1
Egypt                         1
Name: count, dtype: int64

### Задание 2.2

Создайте бинарные признаки is_france, is_italy наподобие признака is_usa

In [46]:
data["is_france"] = data["country"].apply(lambda x: 1 if x == "France" else 0)
data["is_italy"] = data["country"].apply(lambda x: 1 if x == "Italy" else 0)

In [47]:
data["is_france"].sum()

22093

In [48]:
data["is_italy"].sum()

19540

### Задание 2.3

Создайте новый бинарный признак old_wine, где значение 1 будет обозначать, что вино старше 2010 года

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             129971 non-null  int64
 1   country                129908 non-null  object
 2   description            129971 non-null  object
 3   designation            129971 non-null  object
 4   points                 129971 non-null  int64
 5   price                  129971 non-null  float64
 6   province               129908 non-null  object
 7   region_1               129971 non-null  object
 8   taster_name            129971 non-null  object
 9   taster_twitter_handle  129971 non-null  object
 10  title                  129971 non-null  object
 11  variety                129970 non-null  object
 12  winery                 129971 non-null  object
 13  price_round            129971 non-null  int32
 14  year                   125362 non-null  object
 15  is_usa                 129971 non-null  int64
 16  is_france              129971 non-null  int64
 17  is_italy               129971 non-null  int64
 18  old_wine               129971 non-null  int64
dtypes: float64(1), int32(1), int64(6), object(11)
memory usage: 18.3+ MB

In [51]:
data["old_wine"] = data["year"].apply(lambda x: 1 if pd.notnull(x) and int(x) < 2010 else 0)

In [52]:
data["old_wine"].sum()

39781

### Задание 2.7 (Самопроверка)

Создайте новый признак locality из признака title, который будет обозначать название долины/местности производства вина

In [53]:
data["title"].head(5)

0                    Nicosia 2013 Vulkà Bianco  (Etna)
1        Quinta dos Avidagos 2011 Avidagos Red (Douro)
2        Rainstorm 2013 Pinot Gris (Willamette Valley)
3    St. Julian 2013 Reserve Late Harvest Riesling ...
4    Sweet Cheeks 2012 Vintner's Reserve Wild Child...
Name: title, dtype: object

In [ ]:
regex = "\((.*)\)"  # регулярное выражение для нахождения чисел
data["locality"] = data["title"].str.findall(regex).str.get(0)
data.head(3)

,Unnamed: 0,country,description,designation,points,price,province,region_1,taster_name,taster_twitter_handle,title,variety,winery,price_round,year,is_usa,is_france,is_italy,old_wine,locality
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,35.363389,Sicily & Sardinia,Etna,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,35,2013,0,0,1,0,Etna
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.000000,Douro,unknown,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,15,2011,0,0,0,0,Douro
2,2,US,"Tart and snappy, the flavors of lime flesh and...",unknown,87,14.000000,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,14,2013,1,0,0,0,Willamette Valley

:

# 3. Создание признаков. Внешние источники данных